spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAF7Dfs9TZIB/vE1BofX/3iUAg3obRs26UnItd0p3KFoLAKYIT7ZCj9FiCMwY3V0YRXe86ndvpTe8shyAz0fDh03LFq/MHmwfFc0cgGCEzUe6dODefvVy8SwYl3203wI2PyCUqTBIE/kbMyRJF6AGKKJi8w2BQ0RtmiE97m650npP5lUKMuQKmaFMvAibDcDM7i91EqYOclTdur7HXTQkDWIADDWw2i+KRJfkVPiCYwiBgcHuG6YF2b8C8/D6tBMfrhABSUH9R86GZEzQK4620mBMtzjiifXwsCanprhHyxqgaljGSOGY5liFkplyO+4W6K6rYyM/f80e8qGnQBMXZdSABpIySwG7VFH/O/p1WmTyQ2CB3CUdf43HAkjHRbQdU='

token:
  expiration_time: 864000000
  secret: '{cipher}AQAdg6hokFhwfu16b6zhRiPjgwnYLquvxtwxv7XPM5hqzJc+WC8fUjbmw/ViEr9/2ikipng/tN923RHVd1EuNMOlW/84KrAi5qgLCYst20u4DKvWqDxZKEzLWKjZZ46e7OEO6s8xq5yJGtYlZLJCUDYRBQ5KJ0XicW6dHBWOqysvW/UXGEAY3BCwAfv8+2WScupdZvm3jKv8LZwY9smCzb5RFOrxV9oPk1Kv8cavVYXfOj8103XOb7ZEYcZF86WwEoAx+URjequNA5n05QXNRVP8RsmdvPZBhygvkl5h9USVt4vm/D/MxXDkhjNdMDIgqflfGCwl6sPSicBCfPxdK1QSvHKp258ZUxGNWEu6puUE7VQWzA0vXGzph/z0NL/jengW0zQZLB1HRCnSQ2c/GO5v'

gateway:
  ip: 172.18.0.5

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.
